#!/usr/bin/env node
// ctOS setup wizard — takes you from mock data to your real network.
//
//   npm run setup
//
// Detects your network interfaces, asks which ranges you actually administer,
// and writes config/owned-assets.yaml. Ownership is NEVER assumed: every
// network requires an explicit typed confirmation, because that file is the
// scope gate's legal boundary — anything listed there becomes scannable.
import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import readline from 'node:readline/promises';
import { execFile } from 'node:child_process';
import { stdin as input, stdout as output } from 'node:process';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const CONFIG = path.join(ROOT, 'config');

const E = '\x1b[';
const C = {
  hi: `${E}97m`, dim: `${E}38;5;245m`, ok: `${E}38;5;150m`,
  warn: `${E}38;5;214m`, red: `${E}38;5;203m`, off: `${E}0m`,
};
const say = (s = '') => console.log(s);
const rule = () => say(C.dim + '─'.repeat(66) + C.off);

// ── network helpers ─────────────────────────────────────────────────────────
function maskToBits(mask) {
  return mask.split('.').reduce((n, o) => n + ((Number(o) >>> 0).toString(2).match(/1/g) || []).length, 0);
}
function networkAddress(ip, mask) {
  const a = ip.split('.').map(Number), m = mask.split('.').map(Number);
  return a.map((o, i) => o & m[i]).join('.');
}
function detectInterfaces() {
  const out = [];
  for (const [name, addrs] of Object.entries(os.networkInterfaces())) {
    for (const a of addrs || []) {
      if (a.family !== 'IPv4' || a.internal) continue;
      if (!a.netmask) continue;
      const bits = maskToBits(a.netmask);
      out.push({ name, ip: a.address, mask: a.netmask, cidr: `${networkAddress(a.address, a.netmask)}/${bits}` });
    }
  }
  return out;
}

// Flag ranges that are commonly SHARED infrastructure (hotel/campus/carrier),
// where "I administer this" is usually false.
function ownershipRisk(cidr) {
  const [net, bitsStr] = cidr.split('/');
  const bits = Number(bitsStr);
  const o = net.split('.').map(Number);
  if (o[0] === 100 && o[1] >= 64 && o[1] <= 127) return 'carrier-grade NAT (100.64/10) — this is your ISP\'s, not yours';
  if (o[0] === 169 && o[1] === 254) return 'link-local (169.254/16) — no real network here';
  if (bits < 22) return `very large range (/${bits}) — typical of campus/hotel networks you do not administer`;
  return null;
}

function scanArp() {
  return new Promise((resolve) => {
    const win = process.platform === 'win32';
    const cmd = win ? 'arp' : 'arp-scan';
    const args = win ? ['-a'] : ['--localnet', '--quiet'];
    execFile(cmd, args, { timeout: 15000, windowsHide: true }, (err, stdout) => {
      if (err) return resolve({ err, hosts: [] });
      const rows = win
        ? stdout.split('\n').map((l) => l.match(/^\s*(\d+\.\d+\.\d+\.\d+)\s+([0-9a-f]{2}(?:-[0-9a-f]{2}){5})/i))
        : stdout.split('\n').map((l) => l.match(/^(\d+\.\d+\.\d+\.\d+)\s+([0-9a-f:]{17})/i));
      const hosts = rows.filter(Boolean).map((m) => ({ ip: m[1], mac: m[2].replace(/-/g, ':').toLowerCase() }))
        .filter((h) => !(h.mac === 'ff:ff:ff:ff:ff:ff' || h.mac === '00:00:00:00:00:00'
          || h.mac.startsWith('01:00:5e') || h.mac.startsWith('33:33')
          || Number(h.ip.split('.')[0]) >= 224 || h.ip.endsWith('.255')));
      resolve({ err: null, hosts });
    });
  });
}

function inCidr(ip, cidr) {
  const [net, bits] = cidr.split('/');
  const toInt = (s) => s.split('.').reduce((n, o) => (n << 8) + Number(o), 0) >>> 0;
  const mask = Number(bits) === 0 ? 0 : (~0 << (32 - Number(bits))) >>> 0;
  return (toInt(ip) & mask) >>> 0 === (toInt(net) & mask) >>> 0;
}

// ── YAML emit (hand-built so the explanatory comments survive) ──────────────
function buildRegistry({ owner, networks, hosts }) {
  const netBlock = networks.map((n) =>
    `  - cidr: "${n.cidr}"\n    label: "${n.label}"\n    controls_dhcp: ${n.dhcp}`).join('\n');
  const devBlock = hosts.length
    ? hosts.map((h) => `  - id: "${h.mac}"\n    label: "${h.label}"\n    kind: "host"`).join('\n')
    : '  # add devices as you identify them, e.g.\n  # - { id: "aa:bb:cc:dd:ee:01", label: "my-nas", kind: "host" }';

  return `# ─────────────────────────────────────────────────────────────────────────────
# OWNED-ASSET REGISTRY  —  the single source of truth for scope.
#
# Generated by \`npm run setup\`. Every command is validated against this file
# before it executes; a target that is not listed here is denied and logged.
# Only list assets you own or are authorized in writing to control.
# ─────────────────────────────────────────────────────────────────────────────

owner: "${owner}"

# Networks (CIDRs) you administer. Host-class actions must resolve to an IP
# inside one of these ranges or they are denied.
networks:
${netBlock}

# Individual devices. \`id\` is the match key (MAC for hosts, ha:<entity> for
# Home Assistant devices).
devices:
${devBlock}

# Hosts you can control over SSH. Control requires an explicit entry here —
# being inside an owned CIDR is not enough.
hosts: []
  # - { host: "192.168.1.10", user: "admin", label: "my-nas" }

# RFID / NFC card UIDs you physically own. Emulation is additionally gated by
# the jurisdiction profile (rfid_emulation_allowed, ships false).
rfid: []

# Radio. RX is unrestricted. TX also requires jurisdiction.rf.tx_allowed
# (ships false). In the US, 902-928 MHz and 2.4 GHz are broad Part 15.247
# bands, but 433.92 MHz is restricted (Part 15.231/15.240).
rf:
  rx_unrestricted: true
  tx_bands: []
  # - { center_hz: 915000000, bandwidth_hz: 500000, max_erp_dbm: 30, note: "902-928 MHz ISM (Part 15.247)" }

# Financial / cloud accounts read through an official aggregator with YOUR own
# credentials. Secrets live in environment variables, never here.
accounts: []
  # - { id: "acct:checking", provider: "plaid", label: "primary checking" }
`;
}

// ── main ────────────────────────────────────────────────────────────────────
const rl = readline.createInterface({ input, output });
const ask = (q) => rl.question(q);

async function main() {
  say();
  say(`${C.hi}  ctOS setup${C.off} ${C.dim}— from mock data to your real network${C.off}`);
  rule();

  const target = path.join(CONFIG, 'owned-assets.yaml');
  if (fs.existsSync(target)) {
    const a = (await ask(`${C.warn}config/owned-assets.yaml already exists.${C.off} Overwrite? [y/N] `)).trim().toLowerCase();
    if (a !== 'y' && a !== 'yes') { say('Left it alone. Nothing changed.'); return rl.close(); }
  }

  // 1. interfaces
  const ifaces = detectInterfaces();
  if (!ifaces.length) {
    say(`${C.red}No external IPv4 interfaces found.${C.off} Connect to a network and re-run.`);
    return rl.close();
  }
  say(`${C.hi}Detected networks:${C.off}`);
  ifaces.forEach((f, i) => {
    const risk = ownershipRisk(f.cidr);
    say(`  ${C.hi}[${i + 1}]${C.off} ${f.cidr.padEnd(20)} ${C.dim}via ${f.name}  (this machine: ${f.ip})${C.off}`);
    if (risk) say(`      ${C.warn}⚠ ${risk}${C.off}`);
  });
  say(`  ${C.hi}[m]${C.off} enter a CIDR manually`);
  say();

  const pick = (await ask('Which network do you administer? ')).trim().toLowerCase();
  let chosen;
  if (pick === 'm') {
    const c = (await ask('CIDR (e.g. 192.168.1.0/24): ')).trim();
    if (!/^\d+\.\d+\.\d+\.\d+\/\d+$/.test(c)) { say(`${C.red}Not a valid CIDR.${C.off}`); return rl.close(); }
    chosen = { cidr: c, name: 'manual' };
  } else {
    chosen = ifaces[Number(pick) - 1];
    if (!chosen) { say(`${C.red}No such option.${C.off}`); return rl.close(); }
  }

  // 2. THE OWNERSHIP GATE — never assumed, never a bare Enter
  rule();
  say(`${C.warn}  Ownership check${C.off}`);
  say(`  Adding ${C.hi}${chosen.cidr}${C.off} makes every address in it scannable by ctOS.`);
  say(`  Only continue if this is ${C.hi}your own${C.off} network — your home/lab LAN, or one`);
  say(`  you are authorized in writing to administer.`);
  say(`  ${C.dim}Do NOT add a workplace, campus, hotel, cafe or any shared network.${C.off}`);
  const risk = ownershipRisk(chosen.cidr);
  if (risk) say(`  ${C.warn}⚠ ${risk}${C.off}`);
  say();
  const confirm = (await ask(`Type ${C.hi}I OWN THIS${C.off} to confirm (anything else aborts): `)).trim();
  if (confirm.toUpperCase() !== 'I OWN THIS') {
    say(`${C.red}Not confirmed — nothing written.${C.off} The gate stays in demo mode.`);
    return rl.close();
  }
  const label = (await ask('Label for this network [home-lan]: ')).trim() || 'home-lan';
  const dhcp = ((await ask('Do you run DHCP/DNS on it? [y/N] ')).trim().toLowerCase() === 'y');

  // 3. owner name (stamped into every audit entry)
  const owner = (await ask('Your name (stamped into the audit log) [operator]: ')).trim() || 'operator';

  // 4. optional discovery preview
  rule();
  let devices = [];
  const doScan = ((await ask('Scan it now to pre-fill devices? [Y/n] ')).trim().toLowerCase() !== 'n');
  if (doScan) {
    say(`${C.dim}scanning…${C.off}`);
    const { err, hosts } = await scanArp();
    if (err) {
      say(`${C.warn}scan unavailable (${process.platform === 'win32' ? 'arp' : 'arp-scan'} not found or blocked) — skipping.${C.off}`);
    } else {
      const inScope = hosts.filter((h) => inCidr(h.ip, chosen.cidr));
      say(`${C.ok}found ${inScope.length} device(s) in ${chosen.cidr}${C.off}`);
      inScope.forEach((h, i) => say(`  ${String(i + 1).padStart(2)}. ${h.ip.padEnd(16)} ${C.dim}${h.mac}${C.off}`));
      if (inScope.length) {
        const add = ((await ask('Add these to the registry as owned devices? [y/N] ')).trim().toLowerCase() === 'y');
        if (add) devices = inScope.map((h) => ({ mac: h.mac, label: h.ip }));
      }
    }
  }

  // 5. write
  fs.mkdirSync(CONFIG, { recursive: true });
  fs.writeFileSync(target, buildRegistry({
    owner, networks: [{ cidr: chosen.cidr, label, dhcp }], hosts: devices,
  }));
  say();
  say(`${C.ok}wrote${C.off} config/owned-assets.yaml`);

  const jur = path.join(CONFIG, 'jurisdiction.yaml');
  if (!fs.existsSync(jur)) {
    fs.copyFileSync(path.join(CONFIG, 'jurisdiction.example.yaml'), jur);
    say(`${C.ok}wrote${C.off} config/jurisdiction.yaml ${C.dim}(US/FCC, RX-only: TX + emulation + camera all off)${C.off}`);
  }

  rule();
  say(`${C.hi}  Next — run it live:${C.off}`);
  say();
  say(process.platform === 'win32'
    ? `  ${C.hi}$env:INTEGRATION_MODE="live"; npm start${C.off}`
    : `  ${C.hi}INTEGRATION_MODE=live npm start${C.off}`);
  say();
  say(`  The Device Grid and Network Map now show ${C.hi}your real LAN${C.off}.`);
  say(`  ${C.dim}Everything outside ${chosen.cidr} is still denied and logged.${C.off}`);
  say(`  ${C.dim}Verify the gate any time with: npm run check${C.off}`);
  say();
  rl.close();
}

main().catch((e) => { console.error(e); rl.close(); process.exit(1); });
